include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'build/**'
  
  errors:
    # Treat missing return types as errors
    always_declare_return_types: error
    # Treat print statements as warnings
    avoid_print: warning
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat unused imports as info
    unused_import: info

linter:
  rules:
    # Style rules
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - use_key_in_widget_constructors
    
    # Error prevention
    - avoid_empty_else
    - avoid_returning_null_for_future
    - avoid_types_as_parameter_names
    - no_duplicate_case_values
    - throw_in_finally
    - valid_regexps
    
    # Code organization
    - always_put_control_body_on_new_line
    - directives_ordering
    - prefer_relative_imports
    
    # Documentation
    - public_member_api_docs
    
    # Performance
    - use_to_and_as_if_applicable
    
    # Best practices
    - avoid_unnecessary_containers
    - sized_box_for_whitespace
    - use_build_context_synchronously