// lib/builder/editor/new_page_dialog.dart
// Dialog for creating new Builder pages

import 'package:flutter/material.dart';
import '../models/models.dart';
import '../services/services.dart';

/// Dialog for creating a new Builder page
/// 
/// Features:
/// - Page title input
/// - Page ID (auto-generated from title if not provided)
/// - Display location selector (bottomBar, hidden, internal)
/// - Icon picker
/// - Order input
class NewPageDialog extends StatefulWidget {
  final String appId;
  final Function(BuilderPage) onPageCreated;

  const NewPageDialog({
    super.key,
    required this.appId,
    required this.onPageCreated,
  });

  @override
  State<NewPageDialog> createState() => _NewPageDialogState();

  /// Show the dialog and return the created page (or null if cancelled)
  static Future<BuilderPage?> show(
    BuildContext context, {
    required String appId,
  }) async {
    BuilderPage? createdPage;
    
    await showDialog(
      context: context,
      builder: (context) => NewPageDialog(
        appId: appId,
        onPageCreated: (page) {
          createdPage = page;
          Navigator.pop(context);
        },
      ),
    );
    
    return createdPage;
  }
}

class _NewPageDialogState extends State<NewPageDialog> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _pageIdController = TextEditingController();
  final _orderController = TextEditingController(text: '10');
  
  String _displayLocation = 'hidden';
  String _selectedIcon = 'help_outline';
  bool _isCreating = false;
  bool _userHasEditedPageId = false; // Track if user manually edited page ID
  bool _publishImmediately = false; // Whether to publish immediately for bottomBar pages
  
  final BuilderLayoutService _service = BuilderLayoutService();

  // Available icons for selection
  static const List<Map<String, dynamic>> _availableIcons = [
    {'name': 'home', 'icon': Icons.home, 'label': 'Accueil'},
    {'name': 'menu_book', 'icon': Icons.menu_book, 'label': 'Menu'},
    {'name': 'local_offer', 'icon': Icons.local_offer, 'label': 'Promotions'},
    {'name': 'info', 'icon': Icons.info, 'label': 'Info'},
    {'name': 'contact_mail', 'icon': Icons.contact_mail, 'label': 'Contact'},
    {'name': 'star', 'icon': Icons.star, 'label': 'Favoris'},
    {'name': 'favorite', 'icon': Icons.favorite, 'label': 'Favoris cœur'},
    {'name': 'settings', 'icon': Icons.settings, 'label': 'Paramètres'},
    {'name': 'person', 'icon': Icons.person, 'label': 'Profil'},
    {'name': 'shopping_cart', 'icon': Icons.shopping_cart, 'label': 'Panier'},
    {'name': 'card_giftcard', 'icon': Icons.card_giftcard, 'label': 'Cadeau'},
    {'name': 'new_releases', 'icon': Icons.new_releases, 'label': 'Nouveautés'},
    {'name': 'help_outline', 'icon': Icons.help_outline, 'label': 'Aide'},
    {'name': 'article', 'icon': Icons.article, 'label': 'Article'},
    {'name': 'photo_library', 'icon': Icons.photo_library, 'label': 'Galerie'},
  ];

  @override
  void initState() {
    super.initState();
    _titleController.addListener(_onTitleChanged);
    _pageIdController.addListener(_onPageIdEdited);
  }

  @override
  void dispose() {
    _titleController.dispose();
    _pageIdController.dispose();
    _orderController.dispose();
    super.dispose();
  }

  void _onTitleChanged() {
    // Auto-generate page ID from title only if user hasn't manually edited it
    if (!_userHasEditedPageId) {
      final newId = _generatePageId(_titleController.text);
      if (_pageIdController.text != newId) {
        _pageIdController.text = newId;
        // Reset flag since we just auto-updated
        _userHasEditedPageId = false;
      }
    }
  }

  void _onPageIdEdited() {
    // If pageId differs from auto-generated value, mark as manually edited
    final autoGeneratedId = _generatePageId(_titleController.text);
    if (_pageIdController.text != autoGeneratedId) {
      _userHasEditedPageId = true;
    }
  }

  String _generatePageId(String title) {
    return title
        .toLowerCase()
        .replaceAll(RegExp(r'[àáâãäå]'), 'a')
        .replaceAll(RegExp(r'[èéêë]'), 'e')
        .replaceAll(RegExp(r'[ìíîï]'), 'i')
        .replaceAll(RegExp(r'[òóôõö]'), 'o')
        .replaceAll(RegExp(r'[ùúûü]'), 'u')
        .replaceAll(RegExp(r'[ç]'), 'c')
        .replaceAll(RegExp(r'[^a-z0-9]'), '_')
        .replaceAll(RegExp(r'_+'), '_')
        .replaceAll(RegExp(r'^_|_$'), '');
  }

  Future<void> _createPage() async {
    if (!_formKey.currentState!.validate()) return;
    
    setState(() => _isCreating = true);

    try {
      final pageKey = _pageIdController.text.trim();
      final title = _titleController.text.trim();
      final order = int.tryParse(_orderController.text) ?? 10;

      // Try to get system page ID (null for custom pages)
      final systemId = BuilderPageId.tryFromString(pageKey);

      // Create the page with empty blocks
      // Custom pages use /page/<pageKey> route format
      final page = BuilderPage(
        pageKey: pageKey,
        systemId: systemId,
        appId: widget.appId,
        name: title,
        description: 'Page créée depuis le Builder',
        route: systemId != null ? '/${pageKey}' : '/page/$pageKey',
        blocks: [],
        isDraft: true,
        isEnabled: true,
        displayLocation: _displayLocation,
        icon: _selectedIcon,
        order: order,
      );

      // Save as draft
      await _service.saveDraft(page);

      // If publish immediately is checked and display location is bottomBar, publish the page
      if (_publishImmediately && _displayLocation == 'bottomBar') {
        await _service.publishPage(
          page,
          userId: 'system_create',
          shouldDeleteDraft: false,
        );
      }

      if (mounted) {
        final successMessage = _publishImmediately && _displayLocation == 'bottomBar'
            ? '✅ Page "$title" créée et publiée avec succès'
            : '✅ Page "$title" créée avec succès';
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(successMessage)),
        );
        widget.onPageCreated(page);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('❌ Erreur: $e')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isCreating = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Row(
        children: [
          Icon(Icons.add_circle, color: Colors.blue),
          SizedBox(width: 12),
          Text('Créer une nouvelle page'),
        ],
      ),
      content: SizedBox(
        width: 400,
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Title
                TextFormField(
                  controller: _titleController,
                  decoration: const InputDecoration(
                    labelText: 'Titre de la page *',
                    hintText: 'Ex: Nos promotions',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.title),
                  ),
                  validator: (v) => v == null || v.trim().isEmpty 
                      ? 'Le titre est obligatoire' 
                      : null,
                  textCapitalization: TextCapitalization.sentences,
                ),
                const SizedBox(height: 16),

                // Page ID
                TextFormField(
                  controller: _pageIdController,
                  decoration: const InputDecoration(
                    labelText: 'ID de la page',
                    hintText: 'Auto-généré depuis le titre',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.key),
                    helperText: 'Utilisé dans l\'URL: /page/{id}',
                  ),
                  validator: (v) {
                    if (v == null || v.trim().isEmpty) {
                      return 'L\'ID est obligatoire';
                    }
                    // Prevent creating pages with reserved IDs
                    if (BuilderPageId.systemPageIds.contains(v.trim().toLowerCase())) {
                      return 'Cet ID est réservé (home, menu, profile, cart, etc.)';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),

                // Display Location
                DropdownButtonFormField<String>(
                  value: _displayLocation,
                  decoration: const InputDecoration(
                    labelText: 'Emplacement d\'affichage',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.visibility),
                  ),
                  items: const [
                    DropdownMenuItem(value: 'bottomBar', child: Text('Barre de navigation')),
                    DropdownMenuItem(value: 'hidden', child: Text('Caché (accessible via actions)')),
                    DropdownMenuItem(value: 'internal', child: Text('Interne (système)')),
                  ],
                  onChanged: (v) => setState(() => _displayLocation = v ?? 'hidden'),
                ),
                const SizedBox(height: 16),

                // Order (only if bottomBar)
                if (_displayLocation == 'bottomBar') ...[
                  TextFormField(
                    controller: _orderController,
                    decoration: const InputDecoration(
                      labelText: 'Ordre dans la navigation',
                      hintText: 'Ex: 1, 2, 3...',
                      border: OutlineInputBorder(),
                      prefixIcon: Icon(Icons.sort),
                      helperText: 'Plus petit = apparaît en premier',
                    ),
                    keyboardType: TextInputType.number,
                  ),
                  const SizedBox(height: 16),
                  
                  // Publish immediately checkbox for bottomBar pages
                  CheckboxListTile(
                    value: _publishImmediately,
                    onChanged: (v) => setState(() => _publishImmediately = v ?? false),
                    title: const Text('Publier immédiatement'),
                    subtitle: const Text(
                      'La page apparaîtra dans la barre de navigation après publication',
                      style: TextStyle(fontSize: 12),
                    ),
                    controlAffinity: ListTileControlAffinity.leading,
                    contentPadding: EdgeInsets.zero,
                  ),
                  const SizedBox(height: 16),
                ],

                // Icon Picker
                const Text(
                  'Icône',
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.w500,
                    color: Colors.grey,
                  ),
                ),
                const SizedBox(height: 8),
                Wrap(
                  spacing: 8,
                  runSpacing: 8,
                  children: _availableIcons.map((iconData) {
                    final isSelected = _selectedIcon == iconData['name'];
                    return Tooltip(
                      message: iconData['label'] as String,
                      child: InkWell(
                        onTap: () => setState(() => _selectedIcon = iconData['name'] as String),
                        borderRadius: BorderRadius.circular(8),
                        child: Container(
                          width: 44,
                          height: 44,
                          decoration: BoxDecoration(
                            color: isSelected ? Colors.blue.shade100 : Colors.grey.shade100,
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(
                              color: isSelected ? Colors.blue : Colors.grey.shade300,
                              width: isSelected ? 2 : 1,
                            ),
                          ),
                          child: Icon(
                            iconData['icon'] as IconData,
                            color: isSelected ? Colors.blue : Colors.grey.shade700,
                          ),
                        ),
                      ),
                    );
                  }).toList(),
                ),
              ],
            ),
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: _isCreating ? null : () => Navigator.pop(context),
          child: const Text('Annuler'),
        ),
        ElevatedButton.icon(
          onPressed: _isCreating ? null : _createPage,
          icon: _isCreating 
              ? const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(strokeWidth: 2),
                )
              : const Icon(Icons.add),
          label: Text(_isCreating ? 'Création...' : 'Créer la page'),
        ),
      ],
    );
  }
}
